### ISSUE TITLE
extension_paths should have the same behavior as config_paths

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#386]
these configs should behave the same

**Comment by phuonglm** [comment]
Since extension_paths doesn't require must customize, override like the config so here is my proposal:
 + Each teracy-dev, org, project has it own extension file named "Vagrantfile-ext.rb"
 + "Vagrantfile-ext.rb" must place at root of repo.
 + Depend on `config_paths` Vagrant will try to find and load "Vagrantfile-ext.rb" at repo root. ( Eg: `teracy-dev/Vagrantfile-ext.rb` , `teracy-dev/workspace/dev-setup/Vagrantfile-ext.rb`, `teracy-dev/workspace/<project>/Vagrantfile-ext.rb `).
+ After that it still use extension_paths in config file if user want more customize.
+ The list of extesion will follow the order of json file and unique.
@hoale please check if that ok.

**Comment by hoatle** [comment]
@phuonglm:
- each teracy-dev, org or project can OPTIONAL introduces Vagrantfile-ext.rb for deeper customization of the VM
- Vagrantfile-ext.rb must be within the same directory with the vagrant json config file
- Basing on the `config_paths` we will try to load the Vagrantfile-ext.rb file with the specified orders from `config_paths`: the latter will override the former, for example:

```json
"config_paths": [
 "workspace/project-1/vagrant_config_default.json",
 "workspace/project-2/vagrant_config_default.json"
]
```

=> we'll try to autoload with this order so that the latter can override the former when required: <org-dev>/Vagrantfile-ext.rb => <org-dev>/dev-setup/Vagrantfile-ext.rb => <org-dev>/project-1/Vagrantfile-ext.rb => <org-dev>/project-2/Vagrantfile-ext.rb

- we can remove the `extension_paths` config then

**Comment by hoatle** [comment]
@phuonglm I've tried to upgrade my current teracy-dev to the latest develop branch and I got the problem here:

```
macbook-pro:teracy-dev hoatle$ git fetch origin 
macbook-pro:teracy-dev hoatle$ git checkout origin/develop 
Previous HEAD position was 40881cc... Merge pull request #377 from hoavt/tasks/#365-release-v0.5.0-c1
HEAD is now at 15a8fb8... Merge pull request #408 from hieptranquoc/task/#379-should-update-teracy-dev-development-guide
macbook-pro:teracy-dev hoatle$ vagrant status
undefined method `has_key?' for nil:NilClass
from /Users/hoatle/teracy-dev/workspace/dev-setup/vagrant_config_override.json
some errors have occured and '/Users/hoatle/teracy-dev/workspace/dev-setup/vagrant_config_override.json' file will not be used, do you want to continue? [y/N]: n
```

The changes from this issue could be the cause for the problem above.
