### ISSUE TITLE
gitsynch on Windows did not work as expected with private git repos

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#509]
![image](https://user-images.githubusercontent.com/83062/47084740-abfba080-d23e-11e8-9e94-302b0b475025.png)

phuonglm [6:22 PM]
hình như vagrant dùng ssh binary của nó
không phải ssh binary của cygwin
nên lỗi

hoatle [6:31 PM]
ko biết có liên quan tới lỗi này không https://github.com/hashicorp/vagrant/issues/8739#issuecomment-343958840

phuonglm [6:43 PM]
`VAGRANT_PREFER_SYSTEM_BIN=true` la ssh ok

Maybe we should set that env var on Windows system from teracy-dev as default?

**Comment by hoatle** [comment]
related: #508

**Comment by hoatle** [comment]
The bug happened on Cygwin (as we need Cygwin for rsync to work).

**Comment by hoatle** [comment]
we support >= Windows 7, so make sure to test on Windows 7, Windows 10 at least.

**Comment by datphan** [comment]
we should have a docs for cygwin's user since I can not set this `VAGRANT_PREFER_SYSTEM_BIN` to be recognized by `vagrant`


## On Windows

Press `Windows + R` then type `services.msc` and make sure `OpenSSH Authentication Agent` service is set to `manual`

Setup your ssh by following these steps https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/.
Then on cygwin terminal window, type:
```
$ cp -r /cygdrive/c/Users/$USER/.ssh ~/
$ export VAGRANT_PREFER_SYSTEM_BIN=true
$ vagrant status
```

**Comment by hoatle** [comment]
@datphan: please send PR for docs and we’ll let @hoavt to test

**Comment by hoatle** [comment]
@datphan  a section or note for this issue should be documented here https://github.com/teracyhq/dev/blob/develop/docs/getting_started.rst

**Comment by hoatle** [comment]
I guess @hoavt can update and verify the docs by following @datphan' instruction above, so assigned to @hoavt
